config/routes.rb
Rails.application.routes.draw do
   
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:new, :create, :show, :edit, :update] do
    resource :password,
      controller: "clearance/passwords",  
      only: [:create, :edit, :update]

    resources :groceries
    get '/recipes' => "groceries#show_ingredients"
    post '/recipes' => "groceries#recipes"
    get '/result' => "groceries#result"
    get '/expiries' => "groceries#expiries"
    get '/expired' => "groceries#expired"
  end
  
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index"
  
  # CUSTOM ROUTES 
  post '/voice', to: 'groceries#voice_analyse'
  post '/ocr', to: 'groceries#ocr_analyse'
  post '/push', to: 'groceries#push'
  post '/search', to: 'search#identify'
  post '/index_search', to: 'search#find'


end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  mount_uploader :avatar, AvatarUploader

  has_many :groceries, dependent: :destroy
end

app/views/users/_form.html.erb
 <div class="form-group">
    <label for="email">Email address:</label>
    <%= form.text_field :email, class: "form-control", id: "email" %>
  </div>

  <div class="form-group">
    <label for="email">Password:</label>
    <%= form.password_field :password, class: "form-control", id: "pwd" %>
  </div>
  
  <div class="form-group">
    <label for="firstname" class="mr-sm-2">First name:</label>
    <%= form.text_field :first_name, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <label>Last name:</label>
    <%= form.text_field :last_name, class: "form-control" %>
  </div>
  
  <div class="form-group" id="country">
    <label>Country:</label>
    <%= form.select :country, options_for_select(@countries), class: "form-control" %>
  </div>

<div class="avatar-field">
  <%= form.label "Profile picture:" %>
  <%= form.file_field :avatar %>
</div><br/>

<style>
select {
  width: 50%;
}
</style>

<script>
function validateForm() {
    var x = document.getElementById("email").value;
    var y = document.getElementById("pwd").value;
    if (x == "") {
        alert("Email must be filled out");
        return false;
    }

    if (y == "") {
        alert("Password must be filled out");
        return false;
    }
}
</script>

app/views/users/edit.html.erb
<div class="card">
  <div class="box">
    <h2>Update User</h2>
        <hr class="mt-3 mb-2">
    <%= form_for @user, :html => {class:'form-group', onsubmit: 'return validateForm()'} do |form| %>
    <%= render partial: '/users/form', object: form %>
    <%= form.submit 'Save changes', :class => 'btn btn-primary' %>   
    <% end %>
  </div>
</div>


<style>

.card {
    top: 4vh; 
    margin: 0 auto;
    margin-bottom:30px;
    width:350px;
    min-height:300px;
    background:#fff;
    box-shadow: 0.2em 0.2em 0.8em 0.1em rgba(83, 83, 83, 0.3);
    border-radius:0.5em;
    transition:0.5s;
}

.box {
    margin: 20px;
}

</style>

app/views/users/new.html.erb
<div class="card">
  <div class="box">
    <div id="clearance" class="sign-up">
      <h2><%= t(".title") %></h2>
          <hr class="mt-3 mb-2">
        <%= form_for @user, :html => {class:'form-group'} do |form| %>
        <%= render partial: '/users/form', object: form %>
        <%= form.submit 'Sign up', :class => 'btn btn-primary' %>       
      <% end %>


    </div>
  </div>
</div>
<style>

#clearance {
   margin: 20px;
}
.card {
    top: 4vh; 
    margin: 0 auto;
    margin-bottom:30px;
    width:350px;
    min-height:300px;
    background:#fff;
    box-shadow: 0.2em 0.2em 0.8em 0.1em rgba(83, 83, 83, 0.3);
    border-radius:0.5em;
    transition:0.5s;
}


</style>

app/views/users/show.html.erb
<div class-"card-deck">
    <div class="card">
        <div class="box">
            <div class="img mb-1">
                <%= image_tag(@user.avatar? ? @user.avatar.url : asset_path("profilepic.png"), alt: 'Image') %>
            </div>
            <h2 style="font-size: 40px;" > <%=@user.first_name%> <%=@user.last_name%><br></h2>
            <div class= "text">
            <p>Email: <%=@user.email%> </p>
            <p>First name: <%=@user.first_name%> </p>
            <p>Last name: <%=@user.last_name%> </p>
            <p>Country: <%=@user.country%> <p>
            </div>
                <%= link_to 'Edit profile', edit_user_path(@user), class:"btn btn-primary btn-sm" %>
        </div>
    </div>
    <div class='card'>
        <div class='box'>
            <div class='text'>
                <h2>Notifications</h2>
                    <hr class="mt-3 mb-2">
                <p>Be notified of expiring groceries within how many days?</p>
                <%= form_with url: push_path, id:'notif-form', remote: :true do |form| %>   
                    <%=form.number_field( :expire, in: 0...10, class:'form-control', id:'exp-day-input')%><br/>
                    <%=form.submit :Submit, class:'btn btn-primary', id:'submit-btn'%>
                <% end %>
            </div>
        </div>
    </div>
</div>

<style>
.card {
    top:5vh;
    margin: 0 auto;
    margin-bottom: 20px;
    width:350px;
    min-height:30px;
    background:#fff;
    box-shadow: 0.2em 0.2em 0.8em 0.1em rgba(83, 83, 83, 0.3);
    border-radius:0.5em;
    transition:0.5s;
}
.box {
    margin: 20px; 
}
.card:hover {
    box-shadow:0 30px 70px rgba(0,0,0,.2);
}
.card .box .img {
    width:120px;
    height:120px;
    margin:0 auto;
    border-radius:50%;
    overflow:hidden;
}
.card .box .img img {
    width:100%;
    height:100%;
}
.text {
    text-align: left;
    font-size: 15px;
}
h2{
    text-align: center;
}
</style>




<script>
// When serviceWorker is supported, installed, and activated,
// subscribe the pushManager property with the vapidPublicKey
$( document ).ready(function() {
    window.vapidPublicKey = new Uint8Array(<%= @decodedVapidPublicKey %>);
    
    navigator.serviceWorker.ready.then((serviceWorkerRegistration) => {
        serviceWorkerRegistration.pushManager
        .subscribe({
        userVisibleOnly: true,
        applicationServerKey: window.vapidPublicKey
        });
        console.log('pushManager subscribed')
    });



    $('#submit-btn').click(function(e) {
        e.preventDefault();
        var values = $('#exp-day-input').serialize();
        console.log(values)

        navigator.serviceWorker.ready
        .then((serviceWorkerRegistration) => {
          serviceWorkerRegistration.pushManager.getSubscription()
          .then((subscription) => {
            console.log(subscription),
            
      
            fetch('/push', {
            method: 'post',
            body: JSON.stringify({subscription: subscription, expire: {within: values}}),
            headers: {
                'Content-Type': 'application/json',
                'X-CSRF-Token': Rails.csrfToken()
            },
            credentials: 'same-origin'
            })
      
      
          });
        });
      });

});
</script>