config/routes.rb
Rails.application.routes.draw do
   
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:new, :create, :show, :edit, :update] do
    resource :password,
      controller: "clearance/passwords",  
      only: [:create, :edit, :update]

    resources :groceries
    get '/recipes' => "groceries#show_ingredients"
    post '/recipes' => "groceries#recipes"
    get '/result' => "groceries#result"
    get '/expiries' => "groceries#expiries"
    get '/expired' => "groceries#expired"
  end
  
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index"
  
  # CUSTOM ROUTES 
  post '/voice', to: 'groceries#voice_analyse'
  post '/ocr', to: 'groceries#ocr_analyse'
  post '/push', to: 'groceries#push'
  post '/search', to: 'search#identify'
  post '/index_search', to: 'search#find'


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index

        if signed_in?
            @user = current_user.first_name
            @groceries = User.find(current_user.id).groceries
            @exps = []
            @expired = []
            @groceries.each do |grocery|
                if grocery.expiring_within(3)
                    @exps << grocery
                end    
            end

            @groceries.each do |grocery|
                if grocery.expired?
                    @expired << grocery
                end
            end


        elsif current_user == nil
            render 'index_guest'    
        end
    end
    
end

app/views/welcome/index.html.erb
<link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">

<html>
<body>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

<div class="card-deck">

  <% if signed_in? %>
  <div class="card">
  <%= button_to "Add new entry?", new_user_grocery_path(current_user), method: :get,class:"btn btn-outline-primary btn-lg col-12 text-center" %>
  </div>
  <% end %>
<div class="card">
  <div class="box">
      <h3 style="text-align: center;">Welcome, <%= @user %>!</h3>
    <hr class="mt-3 mb-2">
      <p style="text-align: center;" id='date-p'><%=Time.now.strftime("%A, ")%><%=Date.today.to_formatted_s(:rfc822)%></p>
    <hr class="mt-0 mb-2">
      <p><i class="fas fa-cookie" style="font-size:22px"></i>&nbsp;&nbsp;All Groceries:<%= " #{@groceries.count}" %></p>
      <p><i class="fas fa-cookie-bite" style="font-size:22px"></i>&nbsp;&nbsp;Expiring Soon:<%= " #{@exps.count}" %></p>
      <p><i class="fas fa-skull-crossbones" style="font-size:22px"></i>&nbsp;&nbsp;&nbsp;Expired: <%= " #{@expired.count}" %></p>
  </div>
</div>
  <div class="card">
    <div class="box">
      <h4>Check your groceries?</h4>
      <div class="button"><%= button_to "All Groceries", user_groceries_path(current_user), type:"button", class:"btn btn-primary btn-block", method: :get %></div>
      <div class="button"><%= button_to "Expiring Soon", user_expiries_path(current_user), type:"button", class:"btn btn-warning btn-block", method: :get %></div>
      <div id="button1"><%= button_to "Expired", user_expired_path(current_user), type:"button", class:"btn btn-danger btn-block", method: :get %></div>
    </div>
  </div>
</div>
</body>
</html>


<style>


h4, h3 {
  text-align: center;
  font-family: 'Quicksand', sans-serif;
}
.button {
  margin-bottom:10px;
}
#button1 {
  margin:0;
}
.card {   
    top: 3vh;
    margin: 0 auto;
    width:350px;
    min-height:5px;
    background:#fff;
    box-shadow: 0.2em 0.2em 0.8em 0.1em rgba(83, 83, 83, 0.3);
    border-radius:0.5em;
    transition:0.5s;
}

.box {
    margin: 20px;
}
h5 {
  margin: 2px;
  color: white;
}

#date-p {
    font-family: 'Quicksand', sans-serif;
    font-style: italic;
    font-size: 1em;
}

#black {
  color:black;
}
</style>

app/views/welcome/index_guest.html.erb
<link href="https://fonts.googleapis.com/css?family=Heebo:700" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Quicksand:300" rel="stylesheet">

    <div id="mobile">
        <%=image_tag("expr-logo-1309x1309.png", id:'medal-pix', class:'center')%>
        <h3 id='main-title' >Save Your Groceries</h3>
        <h3 id='sub-title' >Be reminded of expiry dates & conquer your fridge.</h3>
    </div>
    <div id='user'>
        <p><strong>Don't have an account?</strong>  <a href="/sign_up" class="btn btn-primary btn-sm">Sign Up</a></p>
        <p><strong>Already a user?</strong>  <a href="/sign_in" class="btn btn-primary btn-sm">Log In</a></p>
    </div>
<style>
body, html {
    height: 100vh;

}
p {
    font-size: 20px;
    margin: 5px;
}
#mobile {
    /* Full height */
    height: 100vh; 
    width: 100vw;

    /* Center and scale the image nicely */
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
    background-image: url(<%= asset_path("mobilebackground.jpg")%>);
    box-shadow: 0 0 0.5em 0.3em rgba(83, 83, 83, 0.7);
    position:absolute;
    top:3em;
}

#sub-title {
    font-family: 'Quicksand';
    font-size: 0.85em;
    text-align:center;
    position: relative;
    top: 5.7em;
    text-shadow: 1px 1px 1px rgba(30,30,30,0.5);
}

#main-title{   
    height: 100px;
    min-width: 350px;
    font-family: 'Heebo';
    font-size: 2em;
    font-weight: bold;
    text-align:center;
    margin:0 auto;
    position: relative;
    top: 4.3em;
    text-shadow: 2px 2px 10px rgba(30,30,30,0.5);
}


#medal-pix {
    width: 9em;
    display: block;
    margin-left: auto;
    margin-right: auto;
    position:relative;
    top: 5.5em;

}

#user{
    position: absolute;
    text-align: center;
    top: 28em;
    margin: 0 auto;
    width: 100vw;
    min-width: 350px;
    text-shadow: 1px 1px 1px rgba(30,30,30,0.5);

}
#user a{
    box-shadow: 0.2em 0.2em 0.8em 0.1em rgba(83, 83, 83, 0.5);
}

#user p {
    margin-bottom: 1em;
    font-size: 0.9em;
}
</style>