config/routes.rb
Rails.application.routes.draw do
   
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:new, :create, :show, :edit, :update] do
    resource :password,
      controller: "clearance/passwords",  
      only: [:create, :edit, :update]

    resources :groceries
    get '/recipes' => "groceries#show_ingredients"
    post '/recipes' => "groceries#recipes"
    get '/result' => "groceries#result"
    get '/expiries' => "groceries#expiries"
    get '/expired' => "groceries#expired"
  end
  
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index"
  
  # CUSTOM ROUTES 
  post '/voice', to: 'groceries#voice_analyse'
  post '/ocr', to: 'groceries#ocr_analyse'
  post '/push', to: 'groceries#push'
  post '/search', to: 'search#identify'
  post '/index_search', to: 'search#find'


end

app/models/grocery.rb
class Grocery < ApplicationRecord
  belongs_to :user

  include PgSearch

  pg_search_scope :search, against: [:ingredient]

  def expiry_countdown
    (self.expired_date - Date.today).to_i
  end

  def expired?
    if Date.today == self.expired_date || Date.today > self.expired_date
      return true
    end
  end

  def expiring_within(days)
    time_count = (self.expired_date - Date.today).to_i
    if (time_count < days && time_count > 0) || time_count == days
      return true
    elsif time_count < 0
      return false
    else
      return false 
    end
  end

  def show_valid_items?
    time_count = (self.expired_date - Date.today).to_i
    if time_count > 0
      return true
    else
      return false
    end
  end
end

app/controllers/groceries_controller.rb
class GroceriesController < ApplicationController

  def index

    @groceries = User.find(params[:user_id]).groceries.order(:expired_date)
  end

  def new
    if params[:item] && params[:expiry_date]
      @voice_preset_new = {item: params[:item].titleize, expiry_date: params[:expiry_date]}
    elsif params[:item]
      @voice_preset_new = {item: params[:item].titleize}
    elsif params[:expiry_date]
      @voice_preset_new = {expiry_date: params[:expiry_date]}
    end

    @grocery = Grocery.new
  end
  
  def create
    @grocery = Grocery.new(grocery_params)
    @grocery.user_id = current_user.id
    if @grocery.save
      redirect_to user_groceries_path
    else
      render 'new'
    end
  end

  
  def ocr_analyse
    file = img_params[:base64]
    data = OcrSpace::FilePost.post('/parse/image', body: { apikey: ENV['OCR_KEY'], language: 'eng', isOverlayRequired: true, base64Image: file })
    parsed_text = data.parsed_response['ParsedResults'][0]["ParsedText"].gsub(/\r|\n/, "")
    @result = date_algo(parsed_text)
    respond_to do |format|
      format.js {render :json => @result}
    end
  end
  
  def voice_analyse
    voice_to_text = voice_params[:value]
    @result_hash = item_date_algo(voice_to_text)
    respond_to do |format|
      format.js {render :json => @result_hash}
    end
  end

  def push
    days_number = push_params[:expire].match(/\d{1,3}/).to_s.to_i
    count = 0
    days_name = 'days'
    groceries = User.find_by(id: current_user.id).groceries
    groceries.each do |g|
      if g.expiring_within(days_number)
        count += 1
      end
      if days_number == 1
        days_name = 'day'
      end
    end
    
    Webpush.payload_send(
      message: "You have #{count} groceries expiring in #{days_number} #{days_name}!",
      endpoint: push_params[:endpoint],
      p256dh: push_params[:p256dh],
      auth: push_params[:auth],
      ttl: 24 * 60 * 60,
      vapid: {
              subject: 'mailto:sender@example.com',
              public_key: ENV['VAPID_PUBLIC_KEY'],
              private_key: ENV['VAPID_PRIVATE_KEY']
              }
    )
  end
  
  def edit
    @grocery = Grocery.find(params[:id])
  end
  
  def update
    @grocery = Grocery.find(params[:id])
    if @grocery.update(grocery_params)
      redirect_to user_groceries_path
    else
      render 'edit'
    end
  end
  
  def destroy
    @grocery = Grocery.find(params[:id])
    @grocery.destroy
    
    redirect_to user_groceries_path
  end
  
  def show_ingredients
    @groceries = User.find(params[:user_id]).groceries.order(:expired_date)
    @valid_items = []
    @groceries.each do |grocery|
      if grocery.show_valid_items? == true
      @valid_items << grocery
      end
    end
  end
  
  def recipes
    
    ingredients = recipe_params.join(',')
    @recipes = Food2Fork::Recipe.search({q: ingredients, sort: 'r', page: 1})
    @recipes.each do |r|
      url_http = r.image_url
      uri = URI.parse(url_http)
      uri.scheme = "https"
      url_https = uri.to_s
      r.image_url = url_https
    end
    @ingredients = recipe_params.join(', ')

    render 'result'
  end

  def expiries
    if params[:days]
      days_to_expiry = params[:days].to_i
      @days = days_to_expiry

      groceries = User.find(params[:user_id]).groceries.order(:expired_date)
      @exps = []
      groceries.each do |grocery|
        if grocery.expiring_within(days_to_expiry) == true
          @exps << grocery
        end
      end
    else
      groceries = User.find(params[:user_id]).groceries.order(:expired_date)
      @exps = []
      groceries.each do |grocery|
        if grocery.expiring_within(3) == true
          @exps << grocery
        end
      end
    end

  end

  def expired
    groceries = User.find(params[:user_id]).groceries.order(:expired_date)
    @expired = []
    groceries.each do |grocery|
      if grocery.expired? == true
        @expired << grocery
      end
    end
  end

  private
  
  def grocery_params
    params.require(:grocery).permit(:ingredient, :expired_date)
  end
  
  def recipe_params
    params.require(:recipe).permit(ingredients:[])[:ingredients]
  end
  # SET THE PARAMS TO RECEIVE AJAX REQUEST OF IMAGE DATA IN BASE64
  def img_params
    params.require(:image).permit(:base64)
  end

  # PARAMS FOR WEB PUSH NOTIF
  def push_params 
    endpoint = params.require(:subscription).permit(:endpoint, :expirationTime, keys:{})[:endpoint]
    p256dh = params.require(:subscription).permit(:endpoint, :expirationTime, keys:{})[:keys][:p256dh]
    auth = params.require(:subscription).permit(:endpoint, :expirationTime, keys:{})[:keys][:auth]
    expire_in = params.require(:expire).permit(:within)[:within]
    hash = {endpoint: endpoint, p256dh: p256dh, auth: auth, expire: expire_in}
  end

  # ALGORITHM TO INTELLIGENTLY FIND DATE
  def date_algo(parsed_text)
    # 1. CHECK IF THERE IS ANY RESULTS IF NOT THEN SKIP ALGORITHM
    expiry_date = ''
    if parsed_text.length > 5 
      text = parsed_text.gsub(/\s+/, '')
      combo1 = /(\d{4})\.\d{2}\.\d{2}/
      combo2 = /\d{2}\.\d{2}\.(\d{4})/
      combo3 = /\d{4}\.\d\.\d{2}/
      combo4 = /\d{2}\.\d\.\d{4}/
      combo5 = /\d{2}\w{3}\d{4}/
      combo6 = /\d{8}/
      combo7 = /\d{6}/

      if text.match?(combo1)
        result = combo1.match(text)[0]
        if result[1].to_i < Date.today.year
          expiry_date = Date.parse(result[2..-1]).to_s
        else
          expiry_date = Date.parse(result).to_s
        end
      elsif text.match?(combo2)
        result = combo2.match(text)[0]
        if result[1].to_i < Date.today.year
          expiry_date = Date.parse(result[0..7]).to_s
        else
          expiry_date = Date.parse(result).to_s
        end

      elsif text.match?(combo3)
        result = combo3.match(text)[0]
        expiry_date = Date.parse(result).to_s

      elsif text.match?(combo4)
        result = combo4.match(text)[0]
        expiry_date = Date.parse(result).to_s

      elsif text.match?(combo5)
        result = combo5.match(text)[0]
        expiry_date = Date.parse(result).to_s

      elsif text.match?(combo6)
        result = combo6.match(text)[0]
        expiry_date = Date.parse(result).to_s

      elsif text.match?(combo7)
        result = combo7.match(text)[0]
        expiry_date = Date.parse(result).to_s
      end
     end

    if expiry_date == ''
      return expiry_date = {error: 1}
    else 
      return {date: expiry_date, error: 0}
    end
  end

  # VOICE RECOGNITION 
  # SET PARAMS TO RECEIVE AJAX REQUEST OF VOICE DATA
  def voice_params
    params.require(:text).permit(:value)
  end

  # ALGORITHM TO INTELLIGENTLY UNDERSTAND TEXT
  def item_date_algo(parsed_text)
    # 'energy bar 12th November 2020'
    # 'pineapple 6th of July 2018'
    # 'raw fish 5th July 2018'
    # 'junk food 11th of May 2019'
    # 'junk food 11 May 2019'
    # 'watermelon 23rd of January 2023'
    # ' raw pork tomorrow'
    # 'Orange next week'
    # ' egg 3 days'


    # DDth(month)YYYY || DD(month)YYYY || Dth(month)YYYY
    months = Date::MONTHNAMES.compact
    item_date = /\d{1,2}(st|nd|rd|th)?(\s?(Of)?)\s(#{months.join('|')})(\s\d{4})?/
    date_only = /^\d{1,2}(st|nd|rd|th)?(\s?(Of)?)\s(#{months.join('|')})(\s\d{4})?$/
    item_tmr = /(Expiring\s)?Tomorrow/
    item_days = /(Expiring\sIn\s)?(\d{1,2})\sDays/
    
    # Capitalises all first character of words only
    text = parsed_text.titleize

    if text.match?(date_only)
      result = text.match(date_only)[0]
      if result.match?(' Of')
        date = result.gsub(' Of','')
      else
        date = result
      end
      expiry_date = Date.parse(date).to_s
    elsif text.match?(item_date)
      result = text.match(item_date)[0]
      if result.match?(' Of')
        date = result.gsub(' Of','')
      else
        date = result
      end
      item_name = text.chomp(result).strip
      expiry_date = Date.parse(date).to_s
    elsif text.match?(item_tmr)
      result = text.match(item_tmr)[0]
      item_name = text.chomp(result).strip
      expiry_date = Date.tomorrow.to_s
    elsif text.match?(item_days)
      result = text.match(item_days)[0]
      days_ahead = text.match(item_days)[2]
      item_name = text.chomp(result).strip
      expiry_date = (Date.today + days_ahead).to_s
    else
      item_name = text.chomp(result)
    end

    if item_name && expiry_date
      return {item: item_name, date: expiry_date, error: 0}
    elsif item_name
      return {item: item_name, error: 0, message:'No expiry date found'}
    elsif expiry_date
      return {date: expiry_date, error: 0, message:'No grocery name found'}
    else
      return {error: 1, message:'Something went wrong.'}
    end
  end
  
end

app/helpers/groceries_helper.rb
module GroceriesHelper
end

app/views/groceries/_voice.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<div>
<div id="voice-record-button">
  <p><font class="fa fa-microphone" id='voice-icon' style="font-size:32px"></font>   Voice Engine</p>
      <div id='voice-output'></div>
  </div>

</div>
<style>
p {
  font-size:1.5em;
}
</style>
<script>
// VOICE RECORDING SEGMENT
// recording voice button added in the HTML side
const ingredient_form = $('#ingredient')
const expiry_date_form = $('#exp-date')
const record_btn = document.querySelector('#voice-record-button')
var SpeechRecognition = SpeechRecognition || webkitSpeechRecognition

var recognition = new SpeechRecognition();
recognition.lang = 'en-US';
recognition.interimResults = false;
recognition.maxAlternatives = 1;

const voice_output = document.querySelector('#voice-output')

record_btn.onclick = function() {
 recognition.start();
 $('#voice-icon').attr("color", "red");
 console.log('Ready to receive a command.');
}

recognition.onresult = function(event) {
 $("#voice-icon").attr("color", "black");
 var last = event.results.length - 1;
 var first_result = event.results[last][0].transcript;
 var confidence = event.results[0][0].confidence
 console.log(first_result+ ', detected with confidence: ' + confidence);

 // send a post request with json object containing the result to be analysed
 // see the post controller private method for algorithm
 // routes added for the /voice with POST method
 fetch('/voice', {
 method: 'post',
 body: JSON.stringify({text: {value: first_result}}),
 headers: {
   'Content-Type': 'application/json',
   'X-CSRF-Token': Rails.csrfToken()
 },
 credentials: 'same-origin'
 }).then(function(response) {
 response.json().then(function(data){
   console.log(data);
   if (data.item && data.date) {
    voice_output.textContent = "Voice: " + data.item + " (Expiry Date: " + data.date + ")",
    expiry_date_form.attr('value',data.date),
    ingredient_form.attr('value',data.item)
   } else if (data.item) {
    voice_output.textContent = "Voice: " + data.item,
    ingredient_form.attr('value',data.item) 
   } else if (data.date) {
    voice_output.textContent = "Expiry Date: " + data.date,
    expiry_date_form.attr('value',data.date)
   }
  })
 })
}

recognition.onspeechend = function() {
 recognition.stop();
}


// VOICE RECORDING FEATURE ENDS
</script>

app/views/groceries/expired.html.erb
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

<div class="card">
  <div class="box">
    <h3>Expired Groceries</h3>
    <table class="table table-hover mt-3">
      <thead>
        <tr>
          <th>Item</th>
          <th style='text-align:center;'>Days Past</th>
          <th style='text-align:center;'>Action</th>
        </tr>
      </thead>
      <tbody>
        <% @expired.each do |exprd,i| %>
          <tr>
            <div>

              <td style='color:red;'><%= exprd.ingredient %></td> 
              <td style='text-align:center;color:red;'><%= -exprd.expiry_countdown %></td>
              <td style='text-align:center;'><%= link_to '<i class="far fa-trash-alt"></i>'.html_safe, user_grocery_path(exprd.user, exprd), method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </div>
        <% end %>
      </tbody>
    </table>
  </div>
</div>


<style>
.card {   
    top: 10vh;
    margin: 0 auto;
    width:350px;
    min-height:5px;
    background:#fff;
    box-shadow: 0.2em 0.2em 0.8em 0.1em rgba(83, 83, 83, 0.3);
    border-radius:0.5em;
    transition:0.5s;
}
.box {
    margin: 20px;
}
</style>

app/views/groceries/expiries.html.erb
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

<div class="card">
  <div class="box">
    <% if @days %>
    <h3>Expiring in <%=@days%> days</h3>
    <% else %>
    <h3>Expiring in 3 days</h3>
    <% end %>

    <div class="ui-widget form-inline mb-2 ">
      <input id="exp-date-input" type="text" placeholder="Other dates.." class='form-control col-9 mr-2 mt-2 mb-2'>
      <button id='exp-find' class='btn-sm btn-primary mr-2 mt-2 mb-2'>Go</button>
    </div>



    <table class="table table-hover">
      <thead>
        <tr>
          <th>Item</th>
          <th>Days Left</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <% @exps.each do |exp,i| %>
          <tr>
            <div>
              <td><%= exp.ingredient %></td> 
              <td style='text-align:center;'><%= exp.expiry_countdown %></td>
              <td><%= link_to '<i class="far fa-trash-alt"></i>'.html_safe, user_grocery_path(exp.user, exp), method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </div>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<style>
.card {   
    top: 3vh;
    margin: 0 auto;
    width:350px;
    min-height:5px;
    background:#fff;
    box-shadow: 0.2em 0.2em 0.8em 0.1em rgba(83, 83, 83, 0.3);
    border-radius:0.5em;
    transition:0.5s;
}
.box {
    margin: 20px;
}

</style>

<script>
  $('#exp-find').click( function() {
    const domain = window.location.origin
    const day_expire = $('#exp-date-input').val()
    console.log(domain + '/users/' + <%= current_user.id%> + '/expires?days=' + day_expire)
    window.location.assign(domain + '/users/' + <%= current_user.id%> + '/expiries?days=' + day_expire)
  });


  $('#exp-date-input').bind("enterKey",function(e){
    const domain = window.location.origin
    const day_expire = $('#exp-date-input').val()
    console.log(domain + '/users/' + <%= current_user.id%> + '/expires?days=' + day_expire)
    window.location.assign(domain + '/users/' + <%= current_user.id%> + '/expiries?days=' + day_expire)    
  });

  // Event when enter is pressed in exp date input form
  $('#exp-date-input').keyup(function(e){
      if(e.keyCode == 13)
      {
          $(this).trigger("enterKey");
      }
  });

</script>

app/views/groceries/index.html.erb
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
<div class="card-deck">
  <div class="card">
    <%= button_to "Create new entry?", new_user_grocery_path, method: :get, class:"btn btn-primary col-12 text-center" %>
  </div>
  <div class="card">
      <%= button_to "No idea what to cook?", user_recipes_path(current_user), method: :get, class:"btn btn-outline-primary col-12 text-center" %>
    </div>


  <div class="card">
    <div class="box">
      <h3>My Groceries</h3>
        <hr class="mt-3 mb-2">
      <p>Today: <%=Time.now.strftime("%A, ")%><%=Date.today.to_formatted_s(:rfc822)%></p>

<div class="ui-widget form-inline mb-2">
  <input id="tags" type="text" placeholder="Search.." class='form-control col-8 mr-2 mb-2'>
  <button id='tag-find' class='btn-sm btn-primary mr-2 mb-2'>Find!</button>
  <button id='stop-search' class='btn-sm btn-default mb-2' style="display: none;">Clear</button>
</div>

        <table class="table table-hover">
      <thead>
        <tr>
          <th>Item</th>
          <th style="text-align:center">Expiry Date</th>
          <th style="text-align:center">Actions</th>
          </tr>
      </thead>

      <tbody id='original-index'>
        <% @groceries.each_with_index do |grocery,i| %>
            <tr data-toggle="collapse" data-target="#entry-<%=i%>" aria-expanded="false" aria-controls="collapseExample">
              <% if grocery.expired?%>
                <td style="color:red"><%=grocery.ingredient%></td>
                <td nowrap style="text-align:center; color:red"><%=grocery.expired_date%></td>
              <% else %>
                <td><%=grocery.ingredient%></td>
                <td nowrap style="text-align:center"><%=grocery.expired_date%></td>
              <% end %>
              <td style="text-align:center"><%= link_to '<i class="far fa-edit"></i>'.html_safe, edit_user_grocery_path(grocery.user, grocery) %>
              &nbsp&nbsp&nbsp<%= link_to '<i class="far fa-trash-alt"></i>'.html_safe, user_grocery_path(grocery.user, grocery), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
      <%# Search results %>
      <tbody id='search-index' style="display: none;">
      </tbody>
      
      </table>
    </div>
  </div>
</div>

<style>
.card {   
    top: 3vh;
    margin: 0 auto;
    width:350px;
    min-height:5px;
    background:#fff;
    box-shadow: 0.2em 0.2em 0.8em 0.1em rgba(83, 83, 83, 0.3);
    border-radius:0.5em;
    transition:0.5s;
}
.box {
    margin: 20px;
}

</style>


<script>
  $( function() {
    var availableTags = [
      <%@groceries.each do |g|%>
        "<%=g.ingredient%>",
      <% end %>
    ];
    $( "#tags" ).autocomplete({
      source: availableTags
    });
  } );

  $('#tag-find').click( function() {
    console.log($('#tags').val())

    $('#tags').removeClass('col-8').addClass('col-6');
    $('#stop-search').show();

    fetch('/index_search', {
        method: 'post',
        body: JSON.stringify({search: {value: $('#tags').val()}}),
        headers: {
            'Content-Type': 'application/json',
            'X-CSRF-Token': Rails.csrfToken()
        },
        credentials: 'same-origin'
        }).then(function(response) {

        response.json().then(function(data){
          $('#original-index').hide()
          $('#search-index').empty()

          $.each(data, function(i,g){
            const today = new Date()
            const day = today.getDate()
            const month = today.getMonth() + 1
            const year = today.getFullYear()
            if (g.expired_date <= (year+'-'+month+'-'+day)) {
              const table_row = $("<tr></tr>")
              const table_data_name = $('<td style="color:red"></td>').html(g.ingredient)
              const table_data_date = $('<td style="text-align:center; color:red"></td>').html(g.expired_date)
              const table_data_btn = $('<td style="text-align:center"></td>').html("<a href=\"/users/<%=current_user.id%>/groceries/"+ g.id +"/edit\"><i class=\"icon-ok icon-white\"></i>	✎</a>" + "&nbsp;&nbsp;&nbsp;" + "<a data-confirm=\"Are you sure?\" rel=\"nofollow\" data-method=\"delete\" href=\"/users/<%=current_user.id%>/groceries/"+ g.id + "\"><i class=\"icon-ok icon-white\"></i>	✘</a>")
              new_table = table_row.append(table_data_name).append(table_data_date).append(table_data_btn)
              $('#search-index').append(new_table)
            }
            else{
              const table_row = $("<tr></tr>")
              const table_data_name = $('<td></td>').html(g.ingredient)
              const table_data_date = $('<td style="text-align:center"></td>').html(g.expired_date)
              const table_data_btn = $('<td style="text-align:center"></td>').html("<a href=\"/users/<%=current_user.id%>/groceries/"+ g.id +"/edit\"><i class=\"icon-ok icon-white\"></i>	✎</a>" + "&nbsp;&nbsp;&nbsp;" + "<a data-confirm=\"Are you sure?\" rel=\"nofollow\" data-method=\"delete\" href=\"/users/<%=current_user.id%>/groceries/"+ g.id + "\"><i class=\"icon-ok icon-white\"></i>	✘</a>")
              new_table = table_row.append(table_data_name).append(table_data_date).append(table_data_btn)
              $('#search-index').append(new_table)            
            }
          })

          $('#search-index').show()

        })
    }) 

  });

  // Return back the old index
  $('#stop-search').click( function() {
    $('#tags').removeClass('col-6').addClass('col-8');
    $('#stop-search').hide();
    $('#original-index').show();
    $('#search-index').empty();
  });

  // Code to run when enter key is run, and has an id enterKey
  $('#tags').bind("enterKey",function(e){
    console.log($('#tags').val())

    $('#tags').removeClass('col-8').addClass('col-6');
    $('#stop-search').show();

    fetch('/index_search', {
        method: 'post',
        body: JSON.stringify({search: {value: $('#tags').val()}}),
        headers: {
            'Content-Type': 'application/json',
            'X-CSRF-Token': Rails.csrfToken()
        },
        credentials: 'same-origin'
        }).then(function(response) {

        response.json().then(function(data){
          $('#original-index').hide()
          $('#search-index').empty()

          $.each(data, function(i,g){
            const today = new Date()
            const day = today.getDate()
            const month = today.getMonth() + 1
            const year = today.getFullYear()
            if (g.expired_date <= (year+'-'+month+'-'+day)) {
              const table_row = $("<tr></tr>")
              const table_data_name = $('<td style="color:red"></td>').html(g.ingredient)
              const table_data_date = $('<td style="text-align:center; color:red"></td>').html(g.expired_date)
              const table_data_btn = $('<td style="text-align:center"></td>').html("<a href=\"/users/<%=current_user.id%>/groceries/"+ g.id +"/edit\"><i class=\"icon-ok icon-white\"></i>	✎</a>" + "&nbsp;&nbsp;&nbsp;" + "<a data-confirm=\"Are you sure?\" rel=\"nofollow\" data-method=\"delete\" href=\"/users/<%=current_user.id%>/groceries/"+ g.id + "\"><i class=\"icon-ok icon-white\"></i>	✘</a>")
              new_table = table_row.append(table_data_name).append(table_data_date).append(table_data_btn)
              $('#search-index').append(new_table)
            }
            else{
              const table_row = $("<tr></tr>")
              const table_data_name = $('<td></td>').html(g.ingredient)
              const table_data_date = $('<td style="text-align:center"></td>').html(g.expired_date)
              const table_data_btn = $('<td style="text-align:center"></td>').html("<a href=\"/users/<%=current_user.id%>/groceries/"+ g.id +"/edit\"><i class=\"icon-ok icon-white\"></i>	✎</a>" + "&nbsp;&nbsp;&nbsp;" + "<a data-confirm=\"Are you sure?\" rel=\"nofollow\" data-method=\"delete\" href=\"/users/<%=current_user.id%>/groceries/"+ g.id + "\"><i class=\"icon-ok icon-white\"></i>	✘</a>")
              new_table = table_row.append(table_data_name).append(table_data_date).append(table_data_btn)
              $('#search-index').append(new_table)            
            }
          })

          $('#search-index').show()

        })
    })  

  });

  // Event when enter is pressed in tags input form
  $('#tags').keyup(function(e){
      if(e.keyCode == 13)
      {
          $(this).trigger("enterKey");
      }
  });
</script>

app/views/groceries/result.html.erb
<h3>Trending Recipies!</h3>
<p>Ingredient(s): <%=@ingredients%></p>
    <hr class="mt-3 mb-2">
<div class="card-deck">
  <% @recipes.each do |recipe| %>
    <div class="card">
      <div class="card-body">
        <%= recipe.title%>
        <img src="<%= recipe.image_url %>" width="100" height="100">
        <p><a href="<%= recipe.source_url%>" target="_blank">Check Out This Recipe!</a></p>
      </div>  
    </div>
  <% end %>
</div>

<style>
h3, p {
  text-align: center;
  margin-top: 30px;

}
.card {   
    top: 4vh;
    margin: 0 auto;
    margin-bottom: 30px;
    min-width:350px;
    max-width:351px;
    min-height:5px;
    background:#fff;
    box-shadow: 0.2em 0.2em 0.8em 0.1em rgba(83, 83, 83, 0.3);
    border-radius:0.5em;
    transition:0.5s;
}
.card-body {
  min-width: 300px;
}
.box {
    margin: 20px;
}
img {
    float:right;
}
</style>

app/views/groceries/show_ingredients.html.erb
<div class="card">
  <div class="box">
    <%= form_with scope: :grocery, url: user_recipes_path(current_user), method: :post, local: true do |form| %>
      <h5 style="text-align:center;">Make a recipe with:</h5>
          <hr class="mt-3 mb-3">
      <% @valid_items.each do |valid_item| %>
        <tr align="left">
          <td><% check_box_tag "ingredients[]", valid_item.ingredient %></td>
          <td><%= check_box('recipe', 'ingredients', {:multiple => true}, valid_item.ingredient, nil) %></td>
          <td><%=valid_item.ingredient %></td>
          <br/>
        </tr>
      <% end %>
      <div id="btn"><br/><%=form.submit "Search Recipes", :class => 'btn btn-primary'%></div>
    <% end %>
  </div>
</div>

<style>
#btn {
  margin-left:3.6em;
}
td {
  text-align: left;
}
.card {
    top:13vh;
    margin: 0 auto;
    width:300px;
    min-height:250px;
    background:#fff;
    box-shadow: 0.2em 0.2em 0.8em 0.1em rgba(83, 83, 83, 0.3);
    border-radius:0.5em;
    transition:0.5s;
}
.box {
  margin:20px;
}

</style>